---
- name: "update and upgrade packages"
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    
  
- name: "install nodejs specific 13.8.0"
  become: yes
  apt:
    name: nodejs=13.8.0
    state: present 

- name: "install npm"
  become: yes
  apt:
    name: npm
    state: present

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present