---
- name: "install dependencies."
  become: yes
  apt:
    name: tar
    state: latest
    update_cache: yes

- name: copy built backend files
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: Extract backend
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz

- name: "install nodejs"
  Shell: |
    apk add --update curl
    apk add --update nodejs npm
    apk add --update npm
    
# - name: "install pm2"
#   become: yes
#   npm:
#     name: pm2
#     global: yes
#     state: present
#     production: yes

- name: Start pm2
  shell: |    
    npm i
    pm2 stop default
    pm2 start npm -- start