---
- name: "install dependencies."
  become: yes
  apt:
    name: ['tar', 'nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    state: present
    production: yes

- name: copy built backend files
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: Extract backend
  shell: |
    cd /home/ubuntu
    tar -xzfv artifact.tar.gz
    rm -rf artifact.tar.gz

- name: Start pm2
  shell: |    
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm -- start